"""m1 capture schema

Revision ID: c5aeedf22a4c
Revises: 
Create Date: 2026-09-24 02:16:38.443785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tw.db.types


# revision identifiers, used by Alembic.
revision: str = 'c5aeedf22a4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('run_after', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', tw.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_run_after'), ['run_after'], unique=False)
        batch_op.create_index('uq_job_open', ['kind', 'ref_id'], unique=True, sqlite_where=sa.text("status IN ('pending','running')"), postgresql_where=sa.text("status IN ('pending','running')"))

    op.create_table('outlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('cms', sa.Text(), nullable=True),
    sa.Column('rss_urls', sa.JSON(), nullable=False),
    sa.Column('sitemap_urls', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('needs_js', sa.Boolean(), nullable=False),
    sa.Column('retain_html', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outlet')),
    sa.UniqueConstraint('slug', name=op.f('uq_outlet_slug'))
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['article.id'], name=op.f('fk_article_merged_into_id_article')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], name=op.f('fk_article_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article')),
    sa.UniqueConstraint('url_hash', name=op.f('uq_article_url_hash'))
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('article_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('first_seen', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_article_url_article_id_article')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_url')),
    sa.UniqueConstraint('url_hash', name=op.f('uq_article_url_url_hash'))
    )
    with op.batch_alter_table('article_url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_url_article_id'), ['article_id'], unique=False)

    op.create_table('fetch_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('vantage', sa.String(length=32), nullable=False),
    sa.Column('started_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_fetch_attempt_article_id_article')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], name=op.f('fk_fetch_attempt_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetch_attempt'))
    )
    with op.batch_alter_table('fetch_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_attempt_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_attempt_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_attempt_started_at'), ['started_at'], unique=False)

    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('fetch_attempt_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fetch_attempt_id'], ['fetch_attempt.id'], name=op.f('fk_listing_fetch_attempt_id_fetch_attempt')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], name=op.f('fk_listing_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing')),
    sa.UniqueConstraint('fetch_attempt_id', name=op.f('uq_listing_fetch_attempt_id'))
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('robots_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('fetch_attempt_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_attempt_id'], ['fetch_attempt.id'], name=op.f('fk_robots_snapshot_fetch_attempt_id_fetch_attempt')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], name=op.f('fk_robots_snapshot_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_robots_snapshot')),
    sa.UniqueConstraint('fetch_attempt_id', name=op.f('uq_robots_snapshot_fetch_attempt_id'))
    )
    with op.batch_alter_table('robots_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robots_snapshot_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('fetch_attempt_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('vantage', sa.String(length=32), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('canonical_link', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('byline', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('modified_at', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_length', sa.Integer(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('headline_hash', sa.String(length=64), nullable=False),
    sa.Column('byline_hash', sa.String(length=64), nullable=False),
    sa.Column('extra_meta', sa.JSON(), nullable=False),
    sa.Column('raw_html_ref', sa.String(length=64), nullable=True),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('normaliser_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_snapshot_article_id_article')),
    sa.ForeignKeyConstraint(['fetch_attempt_id'], ['fetch_attempt.id'], name=op.f('fk_snapshot_fetch_attempt_id_fetch_attempt')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot')),
    sa.UniqueConstraint('fetch_attempt_id', name=op.f('uq_snapshot_fetch_attempt_id'))
    )
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshot_fetched_at'), ['fetched_at'], unique=False)

    op.create_table('archive_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', tw.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('spn_job_id', sa.Text(), nullable=True),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], name=op.f('fk_archive_attempt_snapshot_id_snapshot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_attempt'))
    )
    with op.batch_alter_table('archive_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_attempt_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('listing_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('lastmod', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('fk_listing_entry_listing_id_listing')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_entry'))
    )
    with op.batch_alter_table('listing_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_entry_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_entry_url_hash'), ['url_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_entry_url_hash'))
        batch_op.drop_index(batch_op.f('ix_listing_entry_listing_id'))

    op.drop_table('listing_entry')
    with op.batch_alter_table('archive_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_attempt_snapshot_id'))

    op.drop_table('archive_attempt')
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_snapshot_article_id'))

    op.drop_table('snapshot')
    with op.batch_alter_table('robots_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robots_snapshot_outlet_id'))

    op.drop_table('robots_snapshot')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_listing_fetched_at'))

    op.drop_table('listing')
    with op.batch_alter_table('fetch_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_attempt_started_at'))
        batch_op.drop_index(batch_op.f('ix_fetch_attempt_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_attempt_article_id'))

    op.drop_table('fetch_attempt')
    with op.batch_alter_table('article_url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_url_article_id'))

    op.drop_table('article_url')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_outlet_id'))

    op.drop_table('article')
    op.drop_table('outlet')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('uq_job_open', sqlite_where=sa.text("status IN ('pending','running')"), postgresql_where=sa.text("status IN ('pending','running')"))
        batch_op.drop_index(batch_op.f('ix_job_run_after'))

    op.drop_table('job')
    # ### end Alembic commands ###
