"""m3 annotation table

Revision ID: d6afb792749d
Revises: f58aa13bb287
Create Date: 2026-10-03 15:13:20.314163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tw.db.types


# revision identifiers, used by Alembic.
revision: str = 'd6afb792749d'
down_revision: Union[str, Sequence[str], None] = 'f58aa13bb287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('written_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_annotation_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation'))
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_written_at'), ['written_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_written_at'))
        batch_op.drop_index(batch_op.f('ix_annotation_event_id'))

    op.drop_table('annotation')
    # ### end Alembic commands ###
