"""m2 event table

Revision ID: f58aa13bb287
Revises: c5aeedf22a4c
Create Date: 2026-10-03 14:39:46.143715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tw.db.types


# revision identifiers, used by Alembic.
revision: str = 'f58aa13bb287'
down_revision: Union[str, Sequence[str], None] = 'c5aeedf22a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('detected_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('from_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('to_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('fetch_attempt_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('article_age_at_change', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', tw.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_decision', sa.String(length=16), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', tw.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_event_article_id_article')),
    sa.ForeignKeyConstraint(['fetch_attempt_id'], ['fetch_attempt.id'], name=op.f('fk_event_fetch_attempt_id_fetch_attempt')),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['snapshot.id'], name=op.f('fk_event_from_snapshot_id_snapshot')),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['snapshot.id'], name=op.f('fk_event_to_snapshot_id_snapshot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_article_detected', ['article_id', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_detected_at'))
        batch_op.drop_index(batch_op.f('ix_event_article_id'))
        batch_op.drop_index('ix_event_article_detected')

    op.drop_table('event')
    # ### end Alembic commands ###
